name: dart_ass
description: Advanced ASS Subtitle Reader & Editor for Dart
version: 1.2.0
repository: https://github.com/klsruan/dart_ass

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  dart_freetype: ^1.1.0
  ffi: ^2.1.4
  path: ^1.9.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
